[package]
name = "mingweisamuel"
version = "0.1.0"
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.22"

[profile.release]
opt-level = 3
panic = "abort"

[[bin]]
name = "out"
path = "src/main.rs"
